version: "3"

services:
  backend:
    container_name: backend
    image: b0 #couchdb:3.2.2
    restart: always
    ports:
      - 5984:5984
    volumes:
      # "./budgetzero_data" is where data will persist locally
      - ./budgetzero_data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=admin 
      - COUCHDB_PASSWORD=changeme

  initializer:
    image: curlimages/curl
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - backend
    command: >
      sh -c "curl -u admin:changeme -X PUT backend:5984/budgetzero_default"
      
  frontend:
    container_name: frontend
    image: budgetzero_frontend
    restart: always
    ports:
      - 8080:8080

networks:
  budgetzero_network:
    driver: bridge

