version: "3"

services:
  backend:
    container_name: backend
    image: b0 #couchdb:3.2.2
    restart: always
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin 
      - COUCHDB_PASSWORD=changeme
    # command: sh -c "sleep 15; curl -u admin:changeme -X PUT 127.0.0.1:5984/_users"
    # volumes:
    #   - ./data:/opt/couchdb/data
    # command: ["sh", "-c", "/opt/couchdb/bin/couchdb && curl -X PUT http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@127.0.0.1:5984/_users; curl -X PUT http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@127.0.0.1:5984/_budgets"]

  initializer:
    image: curlimages/curl
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - backend
    command: >
      sh -c "curl -u admin:changeme -X PUT backend:5984/budgetzero_default"
      
  frontend:
    container_name: frontend
    image: budgetzero/budgetzero
    restart: always
    ports:
      - 8080:8080

networks:
  budgetzero_network:
    driver: bridge

