name: run unit tests
on: 
  pull_request:
  push:
    branches:
      - master
      - dev
      - cypress-tests
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Run tests
      run: npm run test:unit
   e2e_test:
    - name: Checkout
      uses: actions/checkout@v2
    # Install NPM dependencies, cache them correctly
    # and run all Cypress tests
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        start: npm start
