name: run unit tests
on: 
  pull_request:
  push:
    branches:
      - master
      - dev
      - cypress-tests
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Run tests
      run: npm run test:unit
