name: build electron apps

on:
  push:
    branches:
      - linux-electron-build

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i

      - name: Build Electron release
        run: npm run electron:build -c.snap.publish=github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
