name: build electron apps

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
        if: ${{ always() }}


      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        if: ${{ always() }}
        with:
          node-version: 10

      - name: Build Electron release
        run: npm run electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
